# Generated by Django 5.2.1 on 2025-06-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
