# Generated by Django 5.2.1 on 2025-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plano_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
