# Generated by Django 5.2.1 on 2025-06-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profissional_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentotransacao',
            name='dados_resposta',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados da Resposta API'),
        ),
        migrations.AddField(
            model_name='pagamentotransacao',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
