# Generated by Django 5.2.1 on 2025-06-21 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagamentotransacao_dados_resposta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('dias_antecedencia', models.IntegerField(default=1)),
                ('horario_envio', models.TimeField(default='09:00')),
                ('template_whatsapp', models.TextField(default='Olá {nome_paciente}! Lembramos que você tem consulta marcada para {data_consulta} às {hora_consulta} na {nome_clinica}. Para cancelar ou reagendar, entre em contato conosco.')),
                ('template_email', models.TextField(default='Olá {nome_paciente}!\n\nEste é um lembrete de sua consulta marcada para:\n\nData: {data_consulta}\nHorário: {hora_consulta}\nLocal: {nome_clinica}\n\nPara cancelar ou reagendar, entre em contato conosco.\n\nAtenciosamente,\nEquipe {nome_clinica}')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('erro', 'Erro'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('mensagem_enviada', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('erro_detalhes', models.TextField(blank=True, null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estabelecimento')),
            ],
        ),
    ]
