# Generated by Django 5.2.1 on 2025-06-22 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracaolembrete_historicolembrete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(help_text='Email do estabelecimento (ex: clinica@gmail.com)', max_length=254)),
                ('email_senha', models.CharField(help_text='Senha de app do Gmail', max_length=200)),
                ('email_smtp', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('email_porta', models.IntegerField(default=587)),
                ('template_assunto', models.CharField(default='Lembrete de Consulta - {nome_clinica}', max_length=200)),
                ('template_corpo', models.TextField(default='Olá {nome_paciente}!\\n\\nLembrete: você tem consulta marcada para {data_consulta} às {hora_consulta} na {nome_clinica}.\\n\\nAtenciosamente,\\nEquipe {nome_clinica}')),
                ('ativo', models.BooleanField(default=False)),
                ('dias_antecedencia', models.IntegerField(default=1)),
                ('horario_envio', models.TimeField(default='09:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estabelecimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.estabelecimento')),
            ],
        ),
    ]
