# Generated by Django 5.2.1 on 2025-06-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracaoemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoemail',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Usar TLS/SSL'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='provedor',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Hotmail'), ('yahoo', 'Yahoo'), ('outro', 'Outro')], default='gmail', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='status_ultimo_teste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='ultimo_teste',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
