# Generated by Django 5.2.1 on 2025-06-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracaoemail_email_use_tls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoemail',
            name='template_corpo',
            field=models.TextField(default='Olá {nome_paciente}! Lembrete: você tem consulta marcada para {data_consulta} às {hora_consulta} na {nome_clinica}. Atenciosamente, Equipe {nome_clinica}'),
        ),
    ]
