# Generated by Django 5.2.1 on 2025-06-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_configuracaoemail_template_corpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaolembrete',
            name='template_email',
            field=models.TextField(default='Olá {nome_paciente}! Este é um lembrete de sua consulta marcada para: Data: {data_consulta} Horário: {hora_consulta} Local: {nome_clinica} Para cancelar ou reagendar, entre em contato conosco. Atenciosamente, Equipe {nome_clinica}'),
        ),
    ]
